[tool.poetry]
name = "terragrunt-deploy"
version = "0.0.1"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
