name: "Execute Terraform & Terragrunt with AWS OIDC"
description: "Sets up Just, Terraform, Terragrunt, and configures AWS OIDC authentication"
inputs:
  just_version:
    description: "Version of Just to install"
    required: false
    default: "1.0.0"
  tf_version:
    description: "Version of Terraform to install"
    required: false
    default: "1.5.7"
  tg_version:
    description: "Version of Terragrunt to install"
    required: false
    default: "0.51.5"
  aws_oidc_role_arn:
    description: "AWS OIDC Role to assume"
    required: true
  aws_region:
    description: "AWS Region"
    required: true
  tg_directory:
    description: "Module directory to preform action upon"
    required: true
  tg_action:
    description: "Terragrunt action to perform (`apply`, `plan`, or `destroy`)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Just
      uses: extractions/setup-just@v2
      with:
        just-version: ${{ inputs.just_version }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf_version }}
        terraform_wrapper: false

    - name: Install Terragrunt
      uses: autero1/action-terragrunt@v1.3.2
      with:
        terragrunt_version: ${{ inputs.tg_version }}

    - name: Configure AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_oidc_role_arn }}
        aws-region: ${{ inputs.aws_region }}

    - name: Set AWS account ID
      shell: bash
      run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)" >> $GITHUB_ENV

    - name: Set git repo name
      shell: bash
      run: echo "GIT_REPO=${{ github.repository }}" >> $GITHUB_ENV

    - name: Ensure Terraform Can Access GitHub
      shell: bash
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - name: Init Terragrunt
      shell: bash
      working-directory: ${{ inputs.tg_directory }}
      run: terragrunt init

    - name: Action Terragrunt
      shell: bash
      working-directory: ${{ inputs.tg_directory }}
      run: terragrunt ${{ inputs.tg_action }} -auto-approve

