name: Deploy Dev
description: Deploy the Dev resources using the dev github environment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - example-queue-processor
    paths-ignore:
      - "pyproject.toml"
  
permissions:
  id-token: write
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
