name: Deploy Dev
description: Deploy the Dev resources using the dev github environment

on:
  workflow_dispatch:
  push:
    branches:
      - github-actions-init

permissions:
    id-token: write
    contents: read

jobs:
  prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
