name: Deploy prod
description: Deploy the Prod resources using the prod github environment

on:
  workflow_dispatch:

jobs:
  prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
