name: Push on main

on:
  push:
    branches:
      - github-actions-init

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    environment:
        name: ci

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/terragrunt_action
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          aws_region: ${{ vars.AWS_REGION }}
          tg_environment: ci
          tg_module: aws/oidc
          action: 'apply --auto-approve'
