name: Init
description: Run ci OIDC and github environment terragrunt module apply

on:
  push:
    branches:
      - github-actions-init

permissions:
  id-token: write
  contents: read

jobs:
  # ci-oidc:
  #   environment:
  #       name: ci

  #   runs-on: ubuntu-latest
  #   env:
  #     ENVIRONMENT_NAME: ci
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/terragrunt_action
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
  #         aws_region: ${{ vars.AWS_REGION }}
  #         tg_directory: infra/live/${{env.ENVIRONMENT_NAME}}/aws/oidc
  #         tg_action: apply

  dev-github:
    # needs: ci-oidc

    environment:
        name: ci

    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: dev
      GITHUB_TOKEN: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4

      - name: test
        shell: bash
        run: |
          curl -s -o /dev/null -w %{http_code} -H "Authorization: token ${{ env.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}"


      # - uses: ./.github/actions/terragrunt_action
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
      #     aws_region: ${{ vars.AWS_REGION }}
      #     tg_directory: infra/live/${{env.ENVIRONMENT_NAME}}/github/environment
      #     tg_action: apply
