name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4    
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          body: |
            See changelog for release notes.
            files: |
            zips/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    permissions:
      id-token: write
      contents: read
    needs: release
    uses: ./.github/workflows/build.yml
    with:
      environment: prod
      version: ${{ inputs.version }}
